---
deployment:
  task:
    - export DEPLOYPATH=/home/matadire/public_html/app.matadirectservice.com
    # - /bin/cp -a * $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    # so this is it really i can feel it.
